DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://www.hashback.org"
enableRobotsTXT = true
googleAnalytics = "UA-106361741-1"
languageCode = "en-us"
theme = "hashback"
title = "Hashback"

[Languages]
[Languages.en]
  weight = 0
  languageName = "English"
[Languages.ru]
  weight = 10
  languageName = "Русский"


[[menu.top]]
	name = "EN"
	url = "/ru"
	weight = -50

	[[menu.top]]
      Name = "Русский"
      parent = "EN"
      identifire = "ru"
      URL = "/ru"
      weight = 0

    [[menu.top]]
      Name = "English"
      parent = "EN"
      identifire = "ru"
      URL = "/"
      weight = 10


[[menu.top]]
	name = "GitHub"
	url = "/github/"
	weight = -60

[[menu.top]]
	name = "Blog"
	url = "/blog/"
	weight = -70

[[menu.top]]
	name = "Development roadmap"
	url = "/development-roadmap/"
	weight = -80

[[menu.top]]
	name = "Team"
	url = "/team/"
	weight = -90

[[menu.top]]
	name = "White paper"
	url = "/white-paper/"
	weight = -100

[[menu.top]]
	name = "Executive summary"
	url = "/executive-summary/"
	weight = -110


[[menu.business]]
name = "Use cases"
url = "/use-cases/"
weight = -70
[[menu.business]]
name = "Benefits"
url = "/benefits/"
weight = -80
[[menu.business]]
name = "Join"
url = "/join/"
weight = -90
[[menu.business]]
name = "Presentation"
url = "/presentation/"
weight = -100

[[menu.developers]]
name = "Technical support"
url = "/support/"
weight = -80
[[menu.developers]]
name = "Hashback API"
url = "/api/"
weight = -90
[[menu.developers]]
name = "Introduction"
url = "/introduction/"
weight = -100

[[menu.project]]
name = "Token"
url = "/token/"
weight = -70
[[menu.project]]
name = "Join the Team"
url = "/join"
weight = -80
[[menu.project]]
name = "Team"
url = "/team/"
weight = -90
[[menu.project]]
name = "White Paper"
url = "/white-paper/"
weight = -100




[params]
background_color_class = "bg-black"
bitcoin = "https://bitcointalk.org/"
description = "Hashback"
facebook = "https://www.facebook.com/hashback.org"
featured_image = "/images/logo.png"
github = "https://www.github.com/hashback"
instagram = ""
medium = "https://medium.com/hashback"
telegram = "https://t.me/Hback"
twitter = "https://twitter.com/Hash_back"
youtube = "https://www.youtube.com/channel/UCMD-YhtX3AAQ-HW2JpJCJUg"
reddit = "https://reddit.com"
