DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://www.hashback.org"
enableRobotsTXT = true
googleAnalytics = "UA-106361741-1"
languageCode = "en-us"
theme = "hashback"
title = "Hashback"

[Languages]
[Languages.en]
  weight = 0
  languageName = "English"
[Languages.ru]
  weight = 10
  languageName = "Русский"


[[menu.lang]]
    name = "current_language"
    weight = 0
    url    = "#"

    [[menu.lang]]
      name = "English"
      parent = "current_language"
      URL = "/"
      weight = 1

    [[menu.lang]]
      name = "Русский"
      parent = "current_language"
      URL = "/ru/"
      weight = 2


[[menu.top]]
	name = "GitHub"
	url = "https://www.github.com/hashback"
	weight = -60

[[menu.top]]
	name = "Blog"
	url = "https://medium.com/hashback/"
	weight = -70

[[menu.top]]
	name = "Development roadmap"
	url = "/development-roadmap/"
	weight = -80

[[menu.top]]
	name = "Team"
	url = "/team/"
	weight = -90

[[menu.top]]
	name = "White paper"
	url = "/white-paper/"
	weight = -100

[[menu.top]]
	name = "Executive summary"
	url = "/executive-summary/"
	weight = -110


[[menu.business]]
name = "Use cases"
url = "/use-cases/"
weight = 4
[[menu.business]]
name = "Benefits"
url = "/benefits/"
weight = 3
[[menu.business]]
name = "Join"
url = "/join/"
weight = 2
[[menu.business]]
name = "Presentation"
url = "/presentation/"
weight = 1

[[menu.developers]]
name = "Technical support"
url = "/support/"
weight = 3
[[menu.developers]]
name = "Hashback API"
url = "/api/"
weight = 2
[[menu.developers]]
name = "Introduction"
url = "/introduction/"
weight = 1

[[menu.project]]
name = "Token"
url = "/token/"
weight = 4
[[menu.project]]
name = "Join the Team"
url = "/join"
weight = 3
[[menu.project]]
name = "Team"
url = "/team/"
weight = 2
[[menu.project]]
name = "White Paper"
url = "/white-paper/"
weight = 1




[params]
background_color_class = "bg-black"
bitcoin = "https://bitcointalk.org/"
description = "Hashback"
facebook = "https://www.facebook.com/hashback.org"
featured_image = "/images/logo.png"
github = "https://www.github.com/hashback"
instagram = ""
medium = "https://medium.com/hashback"
telegram = "https://t.me/Hback"
twitter = "https://twitter.com/Hash_back"
youtube = "https://www.youtube.com/c/HashBack"
gitter = "https://gitter.im/Hashback"
