title = "Hashback"
baseURL = "https://www.hashback.org"
languageCode = "en-us"
theme = "hashback"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  description = "Hashback"
  facebook = "https://www.facebook.com"
  twitter = "https://www.twitter.com"
  medium = "https://www.mwdium.com"
  github = "https://www.github.com"
  bitcoin = "https://www.bitcoin.com"
  telegram = "https://www.telegram.com"
  instagram = ""
  youtube = ""
  featured_image = "/images/logo.png"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"

[[menu.top]]
    name = "Executive summary"
    weight = -110
    url = "/executive-summary/"
    identifier = "executive"
[[menu.top]]
    name = "White paper"
    weight = -100
    url = "/white-paper/"
[[menu.top]]
    name = "Development roadmap"
    weight = -90
    url = "/development-roadmap/"
[[menu.top]]
    name = "Blog"
    weight = -80
    url = "/blog/"
[[menu.top]]
    name = "GitHub"
    weight = -70
    url = "/github/"
[[menu.top]]
    name = "EN"
    weight = -60
    url = "/lang/"

[[menu.developers]]
    name = "Introduction"
    weight = -100
    url = "/introduction/"
[[menu.developers]]
    name = "Hashback API"
    weight = -90
    url = "/api/"
[[menu.developers]]
    name = "Technical support"
    weight = -80
    url = "/support/"

[[menu.business]]
    name = "Presentation"
    weight = -100
    url = "/presentation/"
[[menu.business]]
    name = "Join"
    weight = -90
    url = "/join/"
[[menu.business]]
    name = "Benefits"
    weight = -80
    url = "/benefits/"
[[menu.business]]
    name = "Use cases"
    weight = -70
    url = "/use-cases/"

[[menu.project]]
    name = "White Paper"
    weight = -100
    url = "/white-paper/"
[[menu.project]]
    name = "Team"
    weight = -90
    url = "/team/"
[[menu.project]]
    name = "Join the Team"
    weight = -80
    url = "/join"
[[menu.project]]
    name = "Token"
    weight = -70
    url = "/token/"
